# I.Struktur Data
## 1.List

In [38]:
aList = ["jhon",33,"Taronto", True]

In [39]:
aList

['jhon', 33, 'Taronto', True]

In [40]:
type(aList)

list

In [41]:
bin_colors=['Red','Green','Blue','Yellow']

## 2.Tuples

In [43]:
bin_colors=('Red','Green','Blue','Yellow')
print(f"the second element of the tuple is {bin_colors[1]}")

the second element of the tuple is Green


In [10]:
print(f"the elements after thrid element onwards are {bin_colors[2:]}")

the elements after thrid element onwards are ('Blue', 'Yellow')


In [11]:
nested_tuple = (1,2,(100,200,300),6)
print(f"the maxium value of the inner tuple {max(nested_tuple[2])}")

the maxium value of the inner tuple 300


##  3.Dictionary

In [22]:
bin_colors ={
    "manual_colors": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}

In [23]:
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [24]:
bin_colors.get('approved_color')

'Green'

In [25]:
bin_colors['approved_color']

'Green'

In [26]:
bin_colors['approved_color']="purple"

In [27]:
print(bin_colors)

{'manual_colors': 'Yellow', 'approved_color': 'purple', 'refused_color': 'Red'}


## 4.Sets

In [45]:
green = {'grass', 'leaves'}
print(green)

{'grass', 'leaves'}


In [46]:
yellow = {'dandelions', 'fire hydrant', 'leaves'}
red = {'fire hydrant', 'blood', 'rose', 'leaves'}

In [47]:
print(f"the union of yellow and red sets is {yellow|red}")

the union of yellow and red sets is {'rose', 'blood', 'leaves', 'dandelions', 'fire hydrant'}


In [48]:
print(f"The intersaction of yellow and red is {yellow&red}")

The intersaction of yellow and red is {'fire hydrant', 'leaves'}


## 5.DataFrame

In [63]:
import pandas as pd
df = pd.DataFrame([
    ['1', 'Fares', 32, True],
    ['2', 'Elena', 23, False],
    ['3', 'Steven', 40, True]])
df.columns = ['id', 'name', 'age', 'decision']
print(df)

  id    name  age  decision
0  1   Fares   32      True
1  2   Elena   23     False
2  3  Steven   40      True


In [64]:
df[['name','age']]

name  age
0   Fares   32
1   Elena   23
2  Steven   40

In [65]:
df.iloc[:,3]

0     True
1    False
2     True
Name: decision, dtype: bool

In [66]:
df.iloc[1:3,:]

id    name  age  decision
1  2   Elena   23     False
2  3  Steven   40      True

In [67]:
df[df.age>30]

id    name  age  decision
0  1   Fares   32      True
2  3  Steven   40      True

## 6.Matrix

In [68]:
import numpy as np
myMatrix = np.array([[11, 12, 13], [21,22,23], [31, 32, 33]])

In [69]:
print(myMatrix)

[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [70]:
print(type(myMatrix))

<class 'numpy.ndarray'>


In [71]:
myMatrix.transpose()

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

# Tipe Abstrak
## 1. Vektor

In [72]:
myVector = [22,33,44,55]
print(myVector)

[22, 33, 44, 55]


In [73]:
print(type(myVector))

<class 'list'>


In [74]:
myVector = np.array([22,33,44,55])
print(myVector)

[22 33 44 55]


In [75]:
print(type(myVector))

<class 'numpy.ndarray'>


## 2.stack

In [76]:
class Stack:
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def push(self, item):
        self.items.append(item)
    def pop(self):
        return self.items.pop()
    def peek(self):
        return self.items[len(self.items)-1]
    def size(self):
        return len(self.items)

In [77]:
stack=Stack()
stack.push('Red')
stack.push('Green')
stack.push("Blue")
stack.push("Yellow")

In [78]:
stack.pop()

'Yellow'

In [79]:
stack.isEmpty()

False

In [80]:
colors = ['Red']

In [81]:
colors.append('Green')
colors.append('Yellow')
colors.append('Blue')

In [82]:
colors

['Red', 'Green', 'Yellow', 'Blue']

## 3.Queue

In [83]:
class Queue(object):
    def __init__(self):
        self.items = []
    def isEmpty(self):
        return self.items == []
    def enqueue(self,item):
        self.items.insert(0,item)
    def dequeue(self):
        return self.items.pop()
    def size(self):
        return len(self.items)

In [84]:
queue = Queue()

In [85]:
queue.enqueue("Red")

In [86]:
queue.enqueue('Green')

In [87]:
queue.enqueue('Blue')

In [88]:
queue.enqueue('Yellow')

In [89]:
print(f"Size of queue is {queue.size()}")

Size of queue is 4


In [90]:
print(queue.dequeue())

Red
